### PR TITLE
Loading and Understanding the data

### PR DESCRIPTION
**Pull request by rnavaneeth992**
Issue #5 

I did this using Google Colab 

I used Mathplotlib for plotting the graph and attached some output results

Result2
Result1

### CODE REVIEW

**Comment by breakthe-rule** [comment]
@rnavaneeth992  please check leader board for points

**Comment by rnavaneeth992** [comment]
> @rnavaneeth992 please check leader board for points
Hi Sir, Unable to See 

It is saying 0 PR merged

**Comment by breakthe-rule** [comment]
Will update. Ping me on discord

**Comment by breakthe-rule** [comment]
Correct Prompt is :- Issue: #5 
You used Issue #5 
Bot is unable to address this. Create new PR

**Comment by rnavaneeth992** [comment]
Ok Sure

**Comment by rnavaneeth992** [comment]
> Correct Prompt is :- Issue: #5 You used Issue #5 Bot is unable to address this. Create new PR

Hi I added can you please check it

**Pull request merged**
