### PR TITLE
Added Task1 ipynb file

### PR DESCRIPTION
**Pull request by Subhranil2004**
Issue: #5 
Google colab link: https://drive.google.com/file/d/1zcFv0EcfxsP94rUZTHdzEgcOZNAf59aC/view?usp=sharing
- Updated the code to first resize the images in-place and then add to the list.

### CODE REVIEW

**Comment by Subhranil2004** [comment]
Please consider this PR as it is a updation of my previous code.

**Comment by breakthe-rule** [comment]
@Subhranil2004 send me new pr asap !!!

**Comment by Subhranil2004** [comment]
> @Subhranil2004 send me new pr asap !!!

Sry for replying late but this one is the new pr with the colab link. Can't this be merged? Should I make another new pr?

**Comment by DebjyotiRay** [comment]
Close this PR. And make a new PR with these changes, for the bot to address them and consecutively mark you up in the leaderboard.

**Comment by Subhranil2004** [comment]
Ok got it.

**Pull request closed without merging**
