### PR TITLE
Added Task 1

### PR DESCRIPTION
**Pull request by criticic**
Issue: #5

### CODE REVIEW

**Comment by breakthe-rule** [comment]
@criticic send colab file link

**Comment by criticic** [comment]
https://colab.research.google.com/drive/1MkoeFoD_YTgBg8Oq4lImJoot_ZNXXTd9?usp=sharing

**Comment by breakthe-rule** [comment]
@criticic please grant access to file

**Comment by criticic** [comment]
https://colab.research.google.com/drive/1MkoeFoD_YTgBg8Oq4lImJoot_ZNXXTd9?usp=sharing

does this work?

**Pull request merged**
