### PR TITLE
Create 22155031.txt

### PR DESCRIPTION
**Pull request by Aryan4884**
Issue: #31

### CODE REVIEW

**Comment by breakthe-rule** [comment]
@Aryan4884 you had not dealt with unbalanced data.

Also during train-test-validation split, make a single dataset containing all images and then split it.
Make new PR for augmentation task under issue #33

**Comment by Aryan4884** [comment]
I have done the changes.
Please check.

**Comment by breakthe-rule** [comment]
@Aryan4884 every thing is correct, but note that you have reduced size of image dataset and this may lead to overfitting.

**Comment by breakthe-rule** [comment]
@Aryan4884 follow the template given in Task2_solutions/Example.txt while sending PR for issue #33

**Pull request merged**
